language: rust
rust:
  - nightly
env:
  - FLAGS=
  - FLAGS="--features glium-support"
install:
  - if [ -n "$FLAGS" ]; then sudo apt-get install libXxf86vm-dev; fi
script:
  - cargo build $(echo $FLAGS)
  - cargo test  $(echo $FLAGS)
notifications:
  irc:
    nick: obj-rs
    channels:
      - irc.uriirc.org:16667#hyeon
    template:
      - "#%{build_number} %{result}, %{build_url}"
    skip_join: true
