[package]

name = "obj-rs"
version = "0.4.2"
authors = ["Hyeon Kim <simnalamburt@gmail.com>"]
description   = "Wavefront obj parser for Rust. It handles both 'obj' and 'mtl' formats."
documentation = "https://simnalamburt.github.io/obj-rs"
homepage      = "https://github.com/simnalamburt/obj-rs"
repository    = "https://github.com/simnalamburt/obj-rs"
readme        = "README.md"
keywords      = ["graphics"]
license       = "BSD-2-Clause"

[lib]
name = "obj"

[features]
glium-support = ["glium", "glium_macros"]

[dependencies.glium]
git = "https://github.com/tomaka/glium"
default-features = false
optional = true
[dependencies.glium_macros]
git = "https://github.com/tomaka/glium"
optional = true


[[example]]
name = "glium"

[dev-dependencies.glium]
git = "https://github.com/tomaka/glium"
default-features = false
[dev-dependencies.glutin]
git = "https://github.com/tomaka/glutin"
[dev-dependencies.glium_macros]
git = "https://github.com/tomaka/glium"
